In [ ]:
import numpy as np
marks = np.array([45, 78, 56, 89, 33, 67, 90, 52])

print("Student Marks:", marks)

average = np.mean(marks)
maximum = np.max(marks)
minimum = np.min(marks)

print("\nAverage Marks:", average)
print("Highest Marks:", maximum)
print("Lowest Marks:", minimum)

pass_marks = marks[marks >= 50]
fail_marks = marks[marks < 50]

print("\nPassed Students Marks:", pass_marks)
print("Failed Students Marks:", fail_marks)

print("\nNumber of Passed Students:", len(pass_marks))
print("Number of Failed Students:", len(fail_marks))

Student Marks: [45 78 56 89 33 67 90 52]

Average Marks: 63.75
Highest Marks: 90
Lowest Marks: 33

Passed Students Marks: [78 56 89 67 90 52]
Failed Students Marks: [45 33]

Number of Passed Students: 6
Number of Failed Students: 2


In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
np.array(arr, order='F')
b = arr[:, 1]
c = arr.copy()
print(b,c)

[2 5] [[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([1,2,3])

print(a + b)
print(arr[arr > 3])
print(arr[[0,1], [1,2]])


[[2 4 6]
 [5 7 9]]
[4 5 6]
[2 6]


In [12]:
import pandas as pd
df = pd.read_csv('StudentData.csv')
print(df.head(5))
print(df[df["Hours"]>5])
print(df[(df["Hours"]>5) & (df["Scores"]>70)])
df.info()
df.describe() 
print(df.shape)
print(df.columns)
df.isnull().sum()
df.groupby('Hours')["Scores"].mean()

   Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30
    Hours  Scores
1     5.1      47
3     8.5      75
6     9.2      88
7     5.5      60
8     8.3      81
10    7.7      85
11    5.9      62
15    8.9      95
18    6.1      67
19    7.4      69
23    6.9      76
24    7.8      86
    Hours  Scores
3     8.5      75
6     9.2      88
8     8.3      81
10    7.7      85
15    8.9      95
23    6.9      76
24    7.8      86
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   25 non-null     float64
 1   Scores  25 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 532.0 bytes
(25, 2)
Index(['Hours', 'Scores'], dtype='object')


Hours
1.1    17.0
1.5    20.0
1.9    24.0
2.5    25.5
2.7    27.5
3.2    27.0
3.3    42.0
3.5    30.0
3.8    35.0
4.5    41.0
4.8    54.0
5.1    47.0
5.5    60.0
5.9    62.0
6.1    67.0
6.9    76.0
7.4    69.0
7.7    85.0
7.8    86.0
8.3    81.0
8.5    75.0
8.9    95.0
9.2    88.0
Name: Scores, dtype: float64